spring.application.name=krch
server.port=8443
server.ssl.key-store=file:keystore.p12
server.ssl.key-store-password=krchpassword
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=krch
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=krchuser
spring.datasource.password=krchpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect